# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'simple-notification-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for simple-notification-sample
  pod 'Firebase/Messaging'
end
